version: "3.9"

services:
  postgres:
    image: postgres
    volumes:
      - './01-init.sql:/docker-entrypoint-initdb.d/init-db.sql'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"